### ISSUE TITLE
docker-compose部署青龙之后打不开项目呢

### ISSUE THREAD

**Issue by CoderAWei** [whyour/qinglong#1487]
按照自己的配置修改了``docker-compose.yml``里的``volumes``和``ports``。然后在文件夹路径下运行``docker-compose up -d``之后打开项目``ip:port``，还是不成功呢。是不是漏掉了什么步骤呀

**Comment by CoderAWei** [comment]
我的``yml``配置：
```
version: '2'
services:
  web:
    image: whyour/qinglong:latest
    volumes:
      - ./data:/home/jd_scripts/data
    ports:
      - "0.0.0.0:5825:5825"
    container_name: qinglong2
    restart: unless-stopped

```
