### ISSUE TITLE
青龙面板多开问题

### ISSUE THREAD

**Issue by Luxuslaerm** [whyour/qinglong#1639]
### Qinglong version

2.13.3

### Steps to reproduce

```
version: '2.0'
services:
##第一个青龙
  q1:
    image: whyour/qinglong:latest
    container_name: ql1
    restart: always
    volumes:
       - ./ql1:/ql/data
    ports:
       - 5801:5700
##第二个青龙
  q2:
    image: whyour/qinglong:latest
    container_name: ql2
    restart: always
    volumes:
       - ./ql2:/ql/data
    ports:
       - 5802:5700
##第三个青龙
  q3:
    image: whyour/qinglong:latest
    container_name: ql3
    restart: always
    volumes:
       - ./ql3:/ql/data
    ports:
       - 5803:5700
 ##第四个青龙
  q4:
    image: whyour/qinglong:latest
    container_name: ql4
    restart: always
    volumes:
       - ./ql4:/ql/data
    ports:
       - 5804:5700
```

### What is expected?

根据网上教程用docker compose开了四个青龙面板，但是重启之后面板顺序就错乱了，有没有办法固定容器的顺序？

### What is actually happening?

有一个容器是空的没用，比如说叫它容器3吧，docker重启之后容器顺序就错乱了，原来容器2的日志跑到了容器3中
