### ISSUE TITLE
定时任务执行目录异常，且不会记录执行情况

### ISSUE THREAD

**Issue by WankkoRee** [whyour/qinglong#1757]
### Qinglong version

v2.15.3

### Steps to reproduce

docker compose 拉取的容器，compose 配置有小改动但是应该不影响使用。

```yaml
version: '2'
services:
  qinglong:
    image: whyour/qinglong:2.15.3
    container_name: qinglong
    volumes:
      - ./data:/ql/data
    expose:
      - 5700
    restart: unless-stopped
    networks:
      qinglong_net:
        ipv4_address: 192.168.5.2
networks:
  qinglong_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.5.0/24
          gateway: 192.168.5.1
```

执行脚本是在`脚本管理`中新建的一个`python`脚本，记作`a.py`。

添加的`定时任务`命令是`python a.py`，但是实际上并没有执行。

[docker-entrypoint.sh#L60](https://github.com/whyour/qinglong/blob/092ee89605e3d57b31d2e70bbd3ab4e526e24098/docker/docker-entrypoint.sh#L60) 屏蔽了输出导致无法得知`crontab`真实情况。

将其改为`crond -f >/tmp/cron.log 2>/tmp/cron.err`后，发现日志中有报错说找不到`/root/a.py`，于是推测执行路径有问题（应该是`cron`特性，默认在用户目录执行）。

修改`定时任务`为`cd /ql/data/scripts/ && python a.py`，等待到达预期时间后，发现面板显示的`最后运行时间`并没有改变，但是查看`/tmp/cron.log`日志发现任务已经执行。

此情况与 #1628 类似。

### What is expected?

1. 对于定时任务的执行路径作一定说明，如果是 bug 希望能够排查。
2. 正常显示定时任务的自动执行情况，而非只能显示手动执行的情况。

### What is actually happening?

1. 定时任务使用相对路径时默认起点为用户目录，与预期情况不一致。
2. 不显示定时任务的自动执行时间和日志。
