### ISSUE TITLE
Docker 部署后打开 web 跳转至 /error

### ISSUE THREAD

**Issue by WindSpiritSR** [whyour/qinglong#2193]
### Qinglong version

latest 51c284700116

### Steps to reproduce

`docker-compose.yml`

```yml
version: '3'

services:
  qinglong:
    image: whyour/qinglong:latest
    container_name: qinglong
    hostname: qinglong
    volumes:
      - ./qinglong/data:/ql/data
    links:
      - nginx
    expose:
      - '5700'
    networks:
      net:
        priority: 10
        ipv4_address: xxx.xxx.xxx.xxx
    restart: unless-stopped
    tty: true
```

```shell
root@qinglong:/ql $ pm2 logs
[TAILING] Tailing last 15 lines for [all] processes (change the value with --lines option)
/root/.pm2/pm2.log last 15 lines:
PM2        | 2023-12-02T18:25:38: PM2 log: App [schedule:0] starting in -fork mode-
PM2        | 2023-12-02T18:25:38: PM2 log: App [public:1] starting in -fork mode-
PM2        | 2023-12-02T18:25:39: PM2 log: App [schedule:0] online
PM2        | 2023-12-02T18:25:39: PM2 log: App [panel:2] starting in -fork mode-
PM2        | 2023-12-02T18:25:39: PM2 log: App [public:1] online
PM2        | 2023-12-02T18:25:41: PM2 log: App [panel:2] online

/root/.pm2/logs/schedule-error.log last 15 lines:
/root/.pm2/logs/public-error.log last 15 lines:
/root/.pm2/logs/schedule-out.log last 15 lines:
0|schedule | 2023-12-02T18:25:39: ✌️ 定时服务启动成功！

/root/.pm2/logs/public-out.log last 15 lines:
1|public   | 2023-12-02T18:25:39: ✌️ Sentry loaded
1|public   | 2023-12-02T18:25:39: ✌️ DB loaded
1|public   | 2023-12-02T18:25:39: ✌️ 公共服务启动成功！

/root/.pm2/logs/panel-error.log last 15 lines:
2|panel    | 2023-12-02T18:25:41: ✌️ depInjectorLoader expressLoader initData linkDeps failed Error: 1 CANCELLED: Call cancelled

/root/.pm2/logs/panel-out.log last 15 lines:
2|panel    | 2023-12-02T18:25:40: ✌️ DB loaded
2|panel    | 2023-12-02T18:25:40: ✌️ Init file down
2|panel    | 2023-12-02T18:25:40: ✌️ Sentry loaded
2|panel    | 2023-12-02T18:25:41: ✌️ Dependency Injector loaded
2|panel    | 2023-12-02T18:25:41: ✌️ Express loaded
2|panel    | 2023-12-02T18:25:41: ✌️ 后端服务启动成功！
```

### What is expected?

正常打开 web 面板

### What is actually happening?

Docker 部署后打开 web 跳转至 /error
