### ISSUE TITLE
新版镜像构建容器失败！

### ISSUE THREAD

**Issue by zyj20200** [whyour/qinglong#581]
拉取新版镜像构，docker-compose建容器失败！
docker-compose.yml
```
version: "3.0"

services:
  jdql1:
    image: whyour/qinglong:latest 
    container_name: jdql1 
    restart: always
    ports:
      - "5700:5700"
      - "5701:5701"
    volumes:
      - ./config:/ql/config
      - ./scripts:/ql/scripts
      - ./db:/ql/db
      - ./raw:/ql/raw
      - ./jbot:/ql/jbot
      - ./ninja:/ql/ninja
```
```
(base) ➜  jdql1 docker-compose logs 
Attaching to jdql1
jdql1    | /ql/shell/share.sh: line 319: /ql/log/task_error.log: No such file or directory
jdql1    | /ql/shell/share.sh: line 319: /ql/log/task_error.log: No such file or directory
jdql1    | /ql/shell/share.sh: line 319: /ql/log/task_error.log: No such file or directory
```
