### ISSUE TITLE
可否提供docker-compose.yml

### ISSUE THREAD

**Issue by yw9381** [whyour/qinglong#628]
想要本地运行，但是只有dockefile，而readme中并没有具体的安装部署说明，dockerhub的镜像也完全没有说明这个镜像该如何使用，有哪些环境变量，应该暴露什么端口，希望能够在仓库中提供基于dockerhub镜像的可使用`docker-compose up -d`运行的`docker-compose.yml`文件

**Comment by qingfengfenga** [comment]
```
version: '3'
services:
  ql:
    container_name: qinglong
    image: whyour/qinglong:latest
    restart: always
    ports:
      - "5700:5700"
    volumes:
      - "./log:/ql/log"
      - "./scripts:/ql/scripts"
      - "./jbot:/ql/jbot"
      - "./db:/ql/db"
      - "./config:/ql/config"
```
